#!/usr/bin/bash

git config --global user.name "androidbuild"
git config --global user.email "androidbuild@localhost"
git config --global color.ui false

WD=$PWD
TAG=$(curl -fsS "https://grapheneos.org/releases" \
    | grep -oP "id=[a-z]+-stable><td>[^<]+</td><td><a href=#\K[0-9]{10}" \
    | sort -nr | head -1)
[ -z "$TAG" ] && { echo "ERROR: failed to resolve tag"; exit 1; }

. $WD/common.sh

mkdir -p build/src
cd build/src
repo init --depth=1 --git-lfs \
    --manifest-branch "refs/tags/2026061600" \
    --manifest-url https://github.com/GrapheneOS/platform_manifest.git
mkdir -p .repo/local_manifests
cp -v $WD/configs/manifests/*.xml .repo/local_manifests/

repo sync --force-sync --jobs=4 --no-clone-bundle --no-tags || exit 1  # Probably haven't generated a password from 'https://android.googlesource.com/'

for tier in trebledroid trebledroid-staging rom personal yurei; do
    $WD/patches/apply.sh . "${tier}"
done

if [ "$DEBUG" = "true" ]; then
    $WD/patches/apply.sh . debug-builds
else
    $WD/patches/apply.sh . release-builds
fi
