#!/bin/sh

WD=$PWD
TAG=$(curl -fsS "https://grapheneos.org/releases" \
    | grep -oP "id=[a-z]+-stable><td>[^<]+</td><td><a href=#\K[0-9]{10}" \
    | sort -nr | head -1)
[ -z "$TAG" ] && { echo "ERROR: failed to resolve tag"; exit 1; }

mkdir -p build/src
cd build/src
repo init --depth=1 --git-lfs \
    --manifest-branch "refs/tags/2026061600" \
    --manifest-url https://github.com/GrapheneOS/platform_manifest.git
mkdir -p .repo/local_manifests
cp -v $WD/configs/manifests/*.xml .repo/local_manifests/

.repo/repo/repo sync --force-sync --jobs=4 --no-clone-bundle --no-tags

for tier in trebledroid trebledroid-staging rom personal yuurei; do
    $WD/patches/apply.sh . "${tier}"
done

DEBUG="true"

if [ "$DEBUG" = "true" ]; then
    $WD/patches/apply.sh . debug-builds
else
    $WD/patches/apply.sh . release-builds
fi
