#!/usr/bin/bash

WD=$PWD

cd $WD/build/src/treble_app
bash build.sh release

cd $WD/build/src
prevWD=$PWD
cd device/phh/treble
    cp -fv $WD/configs/rom/rom.mk .
    bash generate.sh rom
cd $prevWD

. build/envsetup.sh

DEBUG="true"

V="user"; [ "$DEBUG" = "true" ] && V="userdebug"

GRAPHENEOS_TAG="2026061600"
AOSP_TAG=$(grep -m1 "aosp_revision:" .repo/manifests/config.yml | sed "s/.*: *//")
ANDROID_VERSION=$(echo "${AOSP_TAG}" | sed "s/android-//;s/_r.*//")
ANDROID_VERSION_TAG=$(grep -m1 "target:" build/release/release_config_map.textproto | sed 's/.*"\([^"]*\)".*/\1/')

lunch "treble_arm64_bvN-${ANDROID_VERSION_TAG}-${V}"
make systemimage -j"$(nproc --all)"
make target-files-package otatools -j"$(nproc --all)"
